### ISSUE TITLE
TypeError: Cannot read property 'prerelease' of null

### ISSUE THREAD

**Issue by PeterDaveHello** [kaelzhang/node-semver-stable#3]
Seems we'll get this error when the input cannot been parsed by semver ...

> TypeError: Cannot read property 'prerelease' of null
>    at repl:1:12
>    at REPLServer.self.eval (repl.js:110:21)
>    at Interface.<anonymous> (repl.js:239:12)
>    at Interface.emit (events.js:95:17)
>    at Interface._onLine (readline.js:203:10)
>    at Interface._line (readline.js:532:8)
>    at Interface._ttyWrite (readline.js:761:14)
>    at ReadStream.onkeypress (readline.js:100:10)
>    at ReadStream.emit (events.js:98:17)
>    at emitKey (readline.js:1096:12)

**Comment by kaelzhang** [comment]
landed in `2.0.4`
